### ISSUE TITLE
Could not satisfy all constraints error in foundry-voting

### ISSUE THREAD

**Issue by hungngdf** [noir-lang/noir-examples#1]
Got error 

```
Error: could not satisfy all constraints

Location:
    crates/nargo_cli/src/cli/mod.rs:72:5
```

when running `nargo prove p` of foundry-voting with `nargo 0.7.1`

**Comment by critesjosh** [comment]
thanks for flagging. we updated the pedersen hash algorithm, so it doesnt work with newer versions. I will update this soon

**Comment by critesjosh** [comment]
should work now with these updates https://github.com/noir-lang/noir-examples/commit/8472f63ca0f057ebcb60440daf25b22292afb087
